### ISSUE TITLE
nPlates 2.0

### ISSUE THREAD

**Issue by Grimsbain** [renstrom/NeavUI#190]
I know I said that nPlates was too much work but with so many people missing it and my dislike for the default nameplates I have been working on a replacement for it. I'm not going to send a pull request for it here because it is far from done but I do have the project up on my github.

https://github.com/Grimsbain/nPlates

It doesn't look like the pre-Legion version but it does fit in better NeavUI and adds some features missing from the default frames. All ingame options apply to the frames and these config options are currently working.

```
nPlates.Config = {
    colorNameWithThreat = true,              -- Colors name by threat. Green = Tanking, Orange = Loosing Threat

    showFullHP = true,
    showLevel = true,
    showServerName = false,
    abbrevLongNames = false,
}
```

Any feedback or help would be appreciated.

**Comment by Technojo01** [comment]
Excellent news, thanks! Will try them tonight!

**Comment by Grimsbain** [comment]
Here is a [screenshot](http://imgur.com/KVD7Gol) of the nameplates in action.

**Comment by Technojo01** [comment]
Upon login

> Message: Interface\AddOns\nPlates\core.lua:193: attempt to index field 'castBar' (a nil value)
Time: 07/25/16 17:31:53
Count: 1
Stack: Interface\AddOns\nPlates\core.lua:193: in function <Interface\AddOns\nPlates\core.lua:159>
[C]: in function `CompactUnitFrame_UpdateName'
Interface\FrameXML\CompactUnitFrame.lua:288: in function `CompactUnitFrame_UpdateAll'
Interface\FrameXML\CompactUnitFrame.lua:171: in function `CompactUnitFrame_SetUnit'
Interface\FrameXML\CompactPartyFrame.lua:5: in function `CompactPartyFrame_OnLoad'
[string "*:OnLoad"]:1: in function <[string "*:OnLoad"]:1>
[C]: in function `CreateFrame'
Interface\FrameXML\CompactPartyFrame.lua:26: in function `CompactPartyFrame_Generate'
...actRaidFrames\Blizzard_CompactRaidFrameContainer.lua:228: in function `CompactRaidFrameContainer_AddGroup'
...actRaidFrames\Blizzard_CompactRaidFrameContainer.lua:215: in function `CompactRaidFrameContainer_AddGroups'
...actRaidFrames\Blizzard_CompactRaidFrameContainer.lua:174: in function `CompactRaidFrameContainer_LayoutFrames'
...actRaidFrames\Blizzard_CompactRaidFrameContainer.lua:130: in function `CompactRaidFrameContainer_TryUpdate'
...actRaidFrames\Blizzard_CompactRaidFrameContainer.lua:76: in function `CompactRaidFrameContainer_SetGroupMode'
...mpactRaidFrames\Blizzard_CompactRaidFrameManager.lua:436: in function <...mpactRaidFrames\Blizzard_CompactRaidFrameManager.lua:427>
...mpactRaidFrames\Blizzard_CompactRaidFrameManager.lua:504: in function `CompactRaidFrameManager_SetSetting'
...rd_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua:579: in function `func'
...rd_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua:556: in function `CompactUnitFrameProfiles_ApplyProfile'
...rd_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua:176: in function `CompactUnitFrameProfiles_ApplyCurrentSettings'
...rd_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua:172: in function `CompactUnitFrameProfiles_ActivateRaidProfile'
...rd_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua:45: in function `CompactUnitFrameProfiles_ValidateProfilesLoaded'
...rd_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua:25: in function <...rd_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua:18>

Locals: frame = CompactPartyFrameMember1 {
 0 = <userdata>
 debuffFrames = <table> {
 }
 maxDispelDebuffs = 0
 inVehicle = false
 background = CompactPartyFrameMember1Background {
 }
 powerBar = CompactPartyFrameMember1PowerBar {
 }
 healthBar = CompactPartyFrameMember1HealthBar {
 }
 overAbsorbGlow = CompactPartyFrameMember1OverAbsorbGlow {
 }
 horizTopBorder = CompactPartyFrameMember1HorizTopBorder {
 }
 vertRightBorder = CompactPartyFrameMember1VertRightBorder {
 }
 myHealPrediction = CompactPartyFrameMember1MyHealPrediction {
 }
 aggroHighlight = CompactPartyFrameMember1AggroHighlight {
 }
 myHealAbsorbRightShadow = CompactPartyFrameMember1MyHealAbsorbRightShadow {
 }
 overHealAbsorbGlow = CompactPartyFrameMember1OverHealAbsorbGlow {
 }
 newUnit = true
 selectionHighlight = CompactPartyFrameMember1SelectionHighlight {
 }
 myHealAbsorbLeftShadow = CompactPartyFrameMember1MyHealAbsorbLeftShadow {
 }
 totalAbsorbOverlay = CompactPartyFrameMember1TotalAbsorbOverlay {
 }
 unit = "player"
 unitExists = true
 statusText = CompactPartyFrameMember1StatusText {
 }
 horizDivider = CompactPartyFrameMember1HorizDivider {
 }
 displayedUnit = "player"
 roleIcon = CompactPartyFrameMember1RoleIcon {
 }
 menu = <function> defined @Interface\FrameXML\CompactUnitFrame.lua:249
 optionTable = <table> {
 }
 otherHealPrediction = CompactPartyFrameMember1OtherHealPrediction {
 }
 dispelDebuffFrames = <table> {
 }
 buffFrames = <table> {
 }
 maxDebuffs = 0
 centerStatusIcon = CompactPartyFrameMember1CenterStatusIcon {
 }
 dropDown = CompactPartyFrameMember1DropDown {
 }
 myHealAbsorb = CompactPartyFrameMember1MyHealAbsorb {
 }
 maxBuffs = 0
 vertLeftBorder = CompactPartyFrameMember1VertLeftBorder {
 }
 horizBottomBorder = CompactPartyFrameMember1HorizBottomBorder {
 }
 name = CompactPartyFrameMe

**Comment by Grimsbain** [comment]
@Technojo01 I just pushed out a bunch of changes hopefully it will work now.

**Comment by Technojo01** [comment]
Still getting the same error, but somewhere else :

> Message: Interface\AddOns\nPlates\core.lua:234: attempt to index field 'castBar' (a nil value)
Time: 07/25/16 17:57:51
Count: 1
Stack: Interface\AddOns\nPlates\core.lua:234: in function <Interface\AddOns\nPlates\core.lua:201>
[C]: in function `CompactUnitFrame_UpdateName'
Interface\FrameXML\CompactUnitFrame.lua:288: in function `CompactUnitFrame_UpdateAll'
Interface\FrameXML\CompactUnitFrame.lua:171: in function `CompactUnitFrame_SetUnit'
Interface\FrameXML\CompactPartyFrame.lua:5: in function `CompactPartyFrame_OnLoad'
[string "*:OnLoad"]:1: in function <[string "*:OnLoad"]:1>
[C]: in function `CreateFrame'
Interface\FrameXML\CompactPartyFrame.lua:26: in function `CompactPartyFrame_Generate'
...actRaidFrames\Blizzard_CompactRaidFrameContainer.lua:228: in function `CompactRaidFrameContainer_AddGroup'
...actRaidFrames\Blizzard_CompactRaidFrameContainer.lua:215: in function `CompactRaidFrameContainer_AddGroups'
...actRaidFrames\Blizzard_CompactRaidFrameContainer.lua:174: in function `CompactRaidFrameContainer_LayoutFrames'
...actRaidFrames\Blizzard_CompactRaidFrameContainer.lua:130: in function `CompactRaidFrameContainer_TryUpdate'
...actRaidFrames\Blizzard_CompactRaidFrameContainer.lua:76: in function `CompactRaidFrameContainer_SetGroupMode'
...mpactRaidFrames\Blizzard_CompactRaidFrameManager.lua:436: in function <...mpactRaidFrames\Blizzard_CompactRaidFrameManager.lua:427>
...mpactRaidFrames\Blizzard_CompactRaidFrameManager.lua:504: in function `CompactRaidFrameManager_SetSetting'
...rd_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua:579: in function `func'
...rd_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua:556: in function `CompactUnitFrameProfiles_ApplyProfile'
...rd_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua:176: in function `CompactUnitFrameProfiles_ApplyCurrentSettings'
...rd_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua:172: in function `CompactUnitFrameProfiles_ActivateRaidProfile'
...rd_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua:45: in function `CompactUnitFrameProfiles_ValidateProfilesLoaded'
...rd_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua:25: in function <...rd_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua:18>

Locals: frame = CompactPartyFrameMember1 {
 0 = <userdata>
 debuffFrames = <table> {
 }
 maxDispelDebuffs = 0
 inVehicle = false
 background = CompactPartyFrameMember1Background {
 }
 powerBar = CompactPartyFrameMember1PowerBar {
 }
 healthBar = CompactPartyFrameMember1HealthBar {
 }
 overAbsorbGlow = CompactPartyFrameMember1OverAbsorbGlow {
 }
 horizTopBorder = CompactPartyFrameMember1HorizTopBorder {
 }
 vertRightBorder = CompactPartyFrameMember1VertRightBorder {
 }
 myHealPrediction = CompactPartyFrameMember1MyHealPrediction {
 }
 aggroHighlight = CompactPartyFrameMember1AggroHighlight {
 }
 myHealAbsorbRightShadow = CompactPartyFrameMember1MyHealAbsorbRightShadow {
 }
 overHealAbsorbGlow = CompactPartyFrameMember1OverHealAbsorbGlow {
 }
 newUnit = true
 selectionHighlight = CompactPartyFrameMember1SelectionHighlight {
 }
 myHealAbsorbLeftShadow = CompactPartyFrameMember1MyHealAbsorbLeftShadow {
 }
 totalAbsorbOverlay = CompactPartyFrameMember1TotalAbsorbOverlay {
 }
 unit = "player"
 unitExists = true
 statusText = CompactPartyFrameMember1StatusText {
 }
 horizDivider = CompactPartyFrameMember1HorizDivider {
 }
 displayedUnit = "player"
 roleIcon = CompactPartyFrameMember1RoleIcon {
 }
 menu = <function> defined @Interface\FrameXML\CompactUnitFrame.lua:249
 optionTable = <table> {
 }
 otherHealPrediction = CompactPartyFrameMember1OtherHealPrediction {
 }
 dispelDebuffFrames = <table> {
 }
 buffFrames = <table> {
 }
 maxDebuffs = 0
 centerStatusIcon = CompactPartyFrameMember1CenterStatusIcon {
 }
 dropDown = CompactPartyFrameMember1DropDown {
 }
 myHealAbsorb = CompactPartyFrameMember1MyHealAbsorb {
 }
 maxBuffs = 0
 vertLeftBorder = CompactPartyFrameMember1VertLeftBorder {
 }
 horizBottomBorder = CompactPartyFrameMember1HorizBottomBorder {
 }
 name = CompactPartyFrameMe

**Comment by Grimsbain** [comment]
Try the newest version I think I got it figured out.

**Comment by Technojo01** [comment]
This is what I get now : [screenshot](https://i.imgur.com/MCdp2C2.png)

**Comment by Grimsbain** [comment]
Did you update the config file and textures? I added an overlay texture and a new option.

**Comment by Technojo01** [comment]
Yes, even deleted nPlates folder first. I'll try to redownload

**Comment by Technojo01** [comment]
Still happens. Got your textureOverlay.tga in the media folder.

**Comment by Grimsbain** [comment]
Did you exit the game and then try?

**Comment by Technojo01** [comment]
Texture OK now after exiting but still getting the same error!

[screenshot](https://i.imgur.com/XjD4S09.png)

**Comment by Grimsbain** [comment]
Can you paste your config file?

**Comment by Technojo01** [comment]
Did not change anything
```
 local _, nPlates = ...

nPlates.Config = {
    colorNameWithThreat = true,              -- Colors name by threat. Green = Tanking, Orange = Loosing Threat

    showFullHP = true,
    showLevel = true,
    showServerName = false,
    abbrevLongNames = false,
}

```

**Comment by Grimsbain** [comment]
Ok, I added a fallback name so it should never show up nil.

**Comment by Technojo01** [comment]
OK no more error! :+1:  

Is it possible to have the threat color for all the plate, not just the name?

**Comment by Grimsbain** [comment]
@Technojo01 Try the new version I think I have that worked out (make sure to update the config file).

**Comment by Technojo01** [comment]
Cool! But getting this error : 

> Message: Interface\AddOns\nPlates\core.lua:257: attempt to index field 'Overlay' (a nil value)
Time: 07/25/16 19:43:50
Count: 1
Stack: Interface\AddOns\nPlates\core.lua:257: in function <Interface\AddOns\nPlates\core.lua:255>
[C]: in function `CompactUnitFrame_UpdateHealthBorder'
Interface\FrameXML\CompactUnitFrame.lua:292: in function `CompactUnitFrame_UpdateAll'
Interface\FrameXML\CompactUnitFrame.lua:171: in function `CompactUnitFrame_SetUnit'
Interface\FrameXML\CompactPartyFrame.lua:5: in function `CompactPartyFrame_OnLoad'
[string "*:OnLoad"]:1: in function <[string "*:OnLoad"]:1>
[C]: in function `CreateFrame'
Interface\FrameXML\CompactPartyFrame.lua:26: in function `CompactPartyFrame_Generate'
...actRaidFrames\Blizzard_CompactRaidFrameContainer.lua:228: in function `CompactRaidFrameContainer_AddGroup'
...actRaidFrames\Blizzard_CompactRaidFrameContainer.lua:215: in function `CompactRaidFrameContainer_AddGroups'
...actRaidFrames\Blizzard_CompactRaidFrameContainer.lua:174: in function `CompactRaidFrameContainer_LayoutFrames'
...actRaidFrames\Blizzard_CompactRaidFrameContainer.lua:130: in function `CompactRaidFrameContainer_TryUpdate'
...actRaidFrames\Blizzard_CompactRaidFrameContainer.lua:76: in function `CompactRaidFrameContainer_SetGroupMode'
...mpactRaidFrames\Blizzard_CompactRaidFrameManager.lua:436: in function <...mpactRaidFrames\Blizzard_CompactRaidFrameManager.lua:427>
...mpactRaidFrames\Blizzard_CompactRaidFrameManager.lua:504: in function `CompactRaidFrameManager_SetSetting'
...rd_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua:579: in function `func'
...rd_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua:556: in function `CompactUnitFrameProfiles_ApplyProfile'
...rd_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua:176: in function `CompactUnitFrameProfiles_ApplyCurrentSettings'
...rd_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua:172: in function `CompactUnitFrameProfiles_ActivateRaidProfile'
...rd_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua:45: in function `CompactUnitFrameProfiles_ValidateProfilesLoaded'
...rd_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua:25: in function <...rd_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua:18>

**Comment by Grimsbain** [comment]
Should be better now. I found out that if oUF_NeavRaid is running it hides some mistakes so I guess I need to test everything with it off.

**Comment by Technojo01** [comment]
All good indeed! You are right, I'm not using neav raid frames. I've should have told you that, sorry!

**Comment by Grimsbain** [comment]
Not your fault. oUF_RaidFrames just does such a job of killing the default raid frames that when you turn it off the nameplates run into errors because the nameplates share code with the raid frames.

**Comment by renstrom** [comment]
@Grimsbain what's the longterm plan for nPlates? Do you intend to merge it back into NeavUI or run it as a stand-alone addon (like you're doing currently)? If the latter, do you want me to include it in upcoming releases or just link to it?

**Comment by renstrom** [comment]
I'm fine with either

**Comment by Grimsbain** [comment]
@renstrom For the sake of ease of development I'm going to keep my own Github and Wowinterface/Curse pages but I'm totally fine with it being included into NeavUI. The development has gotten to the point where all the features are in and it should be bug free.

**Comment by Grimsbain** [comment]
Also having it available as a standalone could help get NeavUI noticed. Because a lot of people will look for a nameplate addon but not everyone will look for full ui packages.
